export const ammanAreas = [
  { value: 'abdoun', ar: 'عبدون', en: 'Abdoun' },
  { value: 'abu-nseir', ar: 'أبو نصير', en: 'Abu Nseir' },
  { value: 'al-jandaweel', ar: 'الجندويل', en: 'Al Jandaweel' },
  { value: 'al-jubeiha', ar: 'الجبيهة', en: 'Al Jubeiha' },
  { value: 'al-kursi', ar: 'الكرسي', en: 'Al Kursi' },
  { value: 'al-madina-al-riyadiya', ar: 'المدينة الرياضية', en: 'Sports City' },
  { value: 'al-rabieh', ar: 'الرابية', en: 'Al Rabieh' },
  { value: 'al-rawnaq', ar: 'الرونق', en: 'Al Rawnaq' },
  { value: 'al-sweifieh', ar: 'الصويفية', en: 'Al Sweifieh' },
  { value: 'al-yasmeen', ar: 'الياسمين', en: 'Al Yasmeen' },
  { value: 'amman-downtown', ar: 'وسط البلد', en: 'Downtown Amman' },
  { value: 'daheit-al-rashid', ar: 'ضاحية الرشيد', en: 'Daheit Al Rashid' },
  { value: 'dabouq', ar: 'دابوق', en: 'Dabouq' },
  { value: 'deir-ghbar', ar: 'دير غبار', en: 'Deir Ghbar' },
  { value: 'jabal-al-hussein', ar: 'جبل الحسين', en: 'Jabal Al Hussein' },
  { value: 'jabal-al-lweibdeh', ar: 'جبل اللويبدة', en: 'Jabal Al Lweibdeh' },
  { value: 'jabal-amman', ar: 'جبل عمّان', en: 'Jabal Amman' },
  { value: 'khalda', ar: 'خلدا', en: 'Khalda' },
  { value: 'marj-al-hamam', ar: 'مرج الحمام', en: 'Marj Al Hamam' },
  { value: 'shafa-badran', ar: 'شفا بدران', en: 'Shafa Badran' },
  { value: 'shmeisani', ar: 'الشميساني', en: 'Shmeisani' },
  { value: 'sweileh', ar: 'صويلح', en: 'Sweileh' },
  { value: 'tabarbour', ar: 'طبربور', en: 'Tabarbour' },
  { value: 'tla-al-ali', ar: 'تلاع العلي', en: 'Tla’ Al Ali' },
  { value: 'umm-al-summaq', ar: 'أم السماق', en: 'Umm Al Summaq' },
  { value: 'umm-uthaina', ar: 'أم أذينة', en: 'Umm Uthaina' },
  { value: 'wadi-al-seer', ar: 'وادي السير', en: 'Wadi Al Seer' },
];
